// Generated by `swift run -c release train-orientation-model`. Do not edit by hand.
// Empty until the model has been trained; the scene detector is disabled while it is empty.
enum SceneModelWeights {
    static let summary = ""
    static let encoded = ""
}
